'use script'


//09.02.2022
/* try{

}
cath(error){
    consol.log(error); - отроботка ошибки
}finally{
    consol.log('все закончилось');
}
если блок try с ошибкой трабатывает блок cath, он передает ему ошибку. А после исполняеться finally
try - catch - finally - если есть ошибка идет схема так
try - finally - отрабатывает если нет ошибки

try - обязательно нужно заполнить и обязательно должин с ним быть catch или finally
*/
// consol.dir() - позволяет более детально смотреть на ошибку 